# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Package Release from Tag

on:
  push:
    tags: [ "*.*.*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }} build
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - env:
        GITHUB_REF: ${{ github.ref }}
      run: |
        mkdir -p build
        node .github/workflows/build.js
        pushd build
        zip -r ../module.zip .
        popd
    - name: Upload Release
      id: upload_release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        files: |
          module.json
          module.zip
    - env:
        GITHUB_REF: ${{ github.ref }}
        FOUNDRY_RELEASE_TOKEN: ${{ secrets.FOUNDRY_RELEASE_TOKEN }}
      run: node .github/workflows/release.js
        
