# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Package Release from Tag

on:
  push:
    tags: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
      with:
        path: release-data
    - uses: actions/checkout@v4
      with:
        ref: module-json
        path: module-json
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        pushd release-data
        ./build.sh
        pushd build
        zip -r ../../build.zip .
        popd
        popd
        rm module-json/module.json
        cp release-data/build/module.json module-json/module.json
        cp module-json/module.json module-json/module-${{ github.ref }}.json
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      
